def painting(lives, difficulty):
    if difficulty == 1:
        if lives == 7:
            print("________      ")
            print("|             ")
            print("|             ")
            print("|             ")
            print("|             ")
            print("|\            ")
        if lives == 6:
            print("________      ")
            print("|      |      ")
            print("|             ")
            print("|             ")
            print("|             ")
            print("|\            ")
        if lives == 5:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|             ")
            print("|             ")
            print("|\            ")
        if lives == 4:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|      |      ")
            print("|             ")
            print("|\            ")
        if lives == 3:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|      ")
            print("|             ")
            print("|\            ")
        if lives == 2:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|             ")
            print("|\            ")
        if lives == 1:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|     /       ")
            print("|\            ")
        if lives == 0:
            print("________   ☆  ")
            print("|      |      ")
            print("|      ツ      ")
            print("|     /|\     ")
            print("|     / \     ")
            print("| 𓍊𓋼𓍊   𓆏  𓋼𓍊")
    if difficulty == 2:
        if lives == 5:
            print("________      ")
            print("|      |      ")
            print("|             ")
            print("|             ")
            print("|             ")
            print("|             ")
        if lives == 4:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|             ")
            print("|             ")
            print("|             ")
        if lives == 3:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|      |      ")
            print("|             ")
            print("|             ")
        if lives == 2:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|      ")
            print("|             ")
            print("|             ")
        if lives == 1:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|             ")
            print("|             ")
        if lives == 0:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|     / \     ")
            print("| 𓍊𓋼𓍊   𓆏  𓋼𓍊")
    if difficulty == 3:
        if lives == 3:
            print("________      ")
            print("|      |      ")
            print("|             ")
            print("|             ")
            print("|             ")
            print("|             ")
        if lives == 2:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|             ")
            print("|             ")
            print("|             ")
        if lives == 1:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|             ")
            print("|             ")
        if lives == 0:
            print("________      ")
            print("|      |      ")
            print("|      0      ")
            print("|     /|\     ")
            print("|     / \     ")
            print("|  ¯\_(ツ)_/¯ ")
def victorypaint():
    print(" 𓆝 𓆟 𓆞 𓆝 𓆟 ")